### PR TITLE
[fix] Use @octokit/auth-app instead of deprecated @octokit/app

### PR DESCRIPTION
**Pull request by alldoami**
Tested and works! Was able to include a test as well but commented it out as I just directly put in secrets inline but didn't want to merge that obviously. If the test deems useful, you could create environment variables for those values to test but I didn't see it worth it.

### CODE REVIEW

**Comment by tibdex** [comment]
Hi @alldoami, thanks for doing this. I would like to make some adjustments before merging. Can you please [allow edits from maintainers](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)?

**Comment by alldoami** [comment]
> Hi @alldoami, thanks for doing this. I would like to make some adjustments before merging. Can you please [allow edits from maintainers](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)?

hmm I don't see that... Could you comment instead and I can fix them?

**Comment by tibdex** [comment]
It would be quicker for both of us if I can push a commit to your branch ;). Can you look again?

**Comment by alldoami** [comment]
From my side I see: 
image

**Comment by tibdex** [comment]
Ok that's weird. I took your commits and added one in #15 that I just merged. You are a co-author of the corresponding squashed commit on the `main` branch: d196e9580c96765a13bf95d632d678789d2a984a. I hope it's OK for you ;)

**Pull request closed without merging**
