### PR TITLE
feat: Upgrade to Node.js 20

### PR DESCRIPTION
**Pull request by freshollie**
You can implement this if you want. Node 16 is EOL

### CODE REVIEW

**Review by tibdex — APPROVED** [review]
Thanks

**Comment by earoberson** [comment]
just a heads up, this is creating issues on self-hosted runners where `node20` is not yet accepted.

**Comment by tibdex** [comment]
Thanks Efrem, I reverted this PR.

**Comment by tibdex** [comment]
https://github.com/actions/runner/pull/2732 added support for Node.js 20 to the GitHub Actions runner.

**Pull request merged**
